(define (domain blocksworld)
  (:requirements :strips :equality)
  (:predicates
    (Arm ?a)
    (Block ?b)
    (Conf ?q)
    (Pose ?o ?p)
    (PushMotion ?a ?o ?p1 ?p2 ?t)
    (Traj ?t)
    (Region ?r)
    (Stackable ?o ?r)
    (FreeMotion ?a ?q1 ?q2 ?t)
    (UnsafePoseObj ?o ?p)
    (ObjCFreePose ?o ?p ?o2 ?p2)
    (UnsafeTrajObj ?a ?t)
    (ObjCFreeTraj ?a ?t ?o ?p)
    (AtConf ?a ?q)
    (AtPose ?o ?p)
    (HandEmpty ?a)
    (CanMove)
    (Supported ?o ?p ?r)
    (On ?o ?r)
  )

  (:action move_free
    :parameters (?a ?q1 ?q2 ?t)
    :precondition (and (Arm ?a) (HandEmpty ?a) (CanMove)
                       (Conf ?q1) (AtConf ?a ?q1)
                       (FreeMotion ?a ?q1 ?q2 ?t)
                       (not (UnsafeTrajObj ?a ?t)))
    :effect (and (AtConf ?a ?q2)
                 (not (AtConf ?a ?q1))
                 (not (CanMove)))
  )

  (:action push
    :parameters (?a ?o ?p1 ?p2 ?t)
    :precondition (and (Arm ?a) (HandEmpty ?a) (CanMove)
                       (Pose ?o ?p1) (AtPose ?o ?p1)
                       (Pose ?o ?p2)
                       (PushMotion ?a ?o ?p1 ?p2 ?t)
                       (not (UnsafePoseObj ?o ?p2))
                       (not (UnsafeTrajObj ?a ?t)))
    :effect (and (AtPose ?o ?p2)
                 (not (AtPose ?o ?p1))
                 (CanMove))
  )

  (:derived (UnsafePoseObj ?o ?p)
    (exists (?o2 ?p2) (and (Pose ?o2 ?p2) (AtPose ?o2 ?p2)
                          (not (= ?o ?o2))
                           (not (ObjCFreePose ?o ?p ?o2 ?p2)))))

  (:derived (UnsafeTrajObj ?a ?t)
    (exists (?o ?p) (and (Pose ?o ?p) (AtPose ?o ?p)
                         (not (ObjCFreeTraj ?a ?t ?o ?p)))))

  (:derived (On ?o ?r)
    (exists (?p) (and (Supported ?o ?p ?r)
                      (AtPose ?o ?p))))
)