(define (domain blocksworld)
  (:requirements :strips :equality)
  (:predicates
    (Arm ?a)
    (Block ?b)
    (Table ?o)
    (Conf ?q)
    (Pose ?o ?p)
    (Grasp ?a ?o ?g)
    (Traj ?t)
    (Region ?r)
    (Stackable ?o ?r)
  
    (Kin ?a ?o ?p ?g ?q ?t)
    (FreeMotion ?a ?q1 ?q2 ?t)
    (HoldingMotion ?a ?q1 ?t ?q2 ?o ?g)
    (UnsafePoseObj ?o ?p)
    (ObjCFreePose ?o ?p ?o2 ?p2)
    (UnsafeTrajObj ?r ?t)
    (ObjCFreeTraj ?r ?t ?o ?p)

    (AtConf ?a ?q)
    (AtPose ?o ?p)
    (AtGrasp ?a ?o ?g)
    (HandEmpty ?a)
    (CanMove)

    (Supported ?o ?p ?r)
    (On ?o ?r)
    (Holding ?o)
  )

  (:action move_free
    :parameters (?a ?q1 ?q2 ?t)
    :precondition (and (Arm ?a) (HandEmpty ?a) (CanMove)
                       (Conf ?q1) (AtConf ?a ?q1)
                       (FreeMotion ?a ?q1 ?q2 ?t)
                       (not (UnsafeTrajObj ?a ?t)))
    :effect (and (AtConf ?a ?q2)
                 (not (AtConf ?a ?q1)) 
                 (not (CanMove)))
  )
  (:action move_holding
    :parameters (?a ?q1 ?q2 ?o ?g ?t)
    :precondition (and (Arm ?a) (CanMove)
                       (Conf ?q1) (AtConf ?a ?q1)
                       (Grasp ?a ?o ?g) (AtGrasp ?a ?o ?g)
                       (HoldingMotion ?a ?q1 ?t ?q2 ?o ?g)
                       (not (UnsafeTrajObj ?a ?t)))
    :effect (and (AtConf ?a ?q2)
                 (not (AtConf ?a ?q1)) 
                 (not (CanMove)))
  )
  (:action pick
    :parameters (?a ?o ?p ?g ?q ?t)
    :precondition (and (Arm ?a) (HandEmpty ?a)
                       (Conf ?q) (AtConf ?a ?q)
                       (Pose ?o ?p) (AtPose ?o ?p)
                       (Kin ?a ?o ?p ?g ?q ?t))
    :effect (and (AtGrasp ?a ?o ?g) 
                 (not (AtPose ?o ?p)) 
                 (not (HandEmpty ?a))
                 (CanMove))
  )
  (:action place
    :parameters (?a ?o ?p ?g ?q ?t)
    :precondition (and (Arm ?a) 
                       (Conf ?q) (AtConf ?a ?q)
                       (Grasp ?a ?o ?g) (AtGrasp ?a ?o ?g)
                       (not (UnsafePoseObj ?o ?p))
                       (Kin ?a ?o ?p ?g ?q ?t))
    :effect (and (not (AtGrasp ?a ?o ?g))
                 (AtPose ?o ?p) 
                 (HandEmpty ?a) 
                 (CanMove))
  )
  (:derived (UnsafePoseObj ?o ?p)
    (exists (?o2 ?p2) (and (Pose ?bo ?p2) (AtPose ?o2 ?p2)
                           (not (ObjCFreePose ?o ?p ?o2 ?p2)))))
  (:derived (UnsafeTrajObj ?r ?t)
      (exists (?o ?p) (and (Pose ?o ?p) (AtPose ?o ?p)
                           (not (Holding ?o))
                           (not (ObjCFreeTraj ?r ?t ?o ?p)))))
  (:derived (On ?o ?r)
    (exists (?p) (and (Supported ?o ?p ?r)
                      (AtPose ?o ?p)))
  )
  (:derived (Holding ?o)
    (exists (?a ?g) (and (Arm ?a) 
                         (Grasp ?a ?o ?g)
                         (AtGrasp ?a ?o ?g)))
  )
)
