(define (stream block-stacking)
  (:stream sample-pose-block
    :inputs (?o1 ?o2 ?p2)
    :domain (and (Block ?o1) (Block ?o2) (Pose ?o2 ?p2))
    :outputs (?p1)
    :certified (and (Pose ?o1 ?p1) (Supported ?o1 ?p1 ?o2 ?p2))
  )
  (:stream sample-pose-table
    :inputs (?o1 ?o2 ?p2)
    :domain (and (Block ?o1) (Table ?o2) (Pose ?o2 ?p2))
    :outputs (?p1)
    :certified (and (Pose ?o1 ?p1) (Supported ?o1 ?p1 ?o2 ?p2))
  )
  (:stream sample-grasp
    :inputs (?a ?o)
    :domain (and (Arm ?a) (Graspable ?o))
    :outputs (?g)
    :certified (Grasp ?o ?g)
  ) 
  (:stream inverse-kinematics
    :inputs (?a ?o ?p ?g)
    :domain (and (Arm ?a) (Pose ?o ?p) (Grasp ?o ?g))
    :outputs (?q ?t)
    :certified (and (Conf ?q) (Traj ?t) (Kin ?o ?p ?g ?q ?t))
  )
  (:stream plan-free-motion
    :inputs (?a ?q1 ?q2)
    :domain (and (Arm ?a) (Conf ?q1) (Conf ?q2))
    :outputs (?t)
    :certified (and (Traj ?t) (FreeMotion ?q1 ?t ?q2))
  )
  (:stream plan-holding-motion
    :inputs (?a ?q1 ?q2 ?o ?g)
    :domain (and (Arm ?a) (Conf ?q1) (Conf ?q2) (Grasp ?o ?g))
    :outputs (?t)
    :certified (and (Traj ?t) (HoldingMotion ?q1 ?t ?q2 ?o ?g))
  )
  (:stream test-traj-cfree
    :inputs (?a ?t ?o ?p)
    :domain (and (Arm ?a) (Traj ?t) (Pose ?o ?p))
    :certified (ObjCFreeTraj ?a ?t ?o ?p)
  )
)
